# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{wepawet}
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Lee"]
  # s.cert_chain = ["/Users/chris/Documents/projects/rubygems/wepawet/../gem-public_cert.pem"]
  s.date = %q{2011-05-11}
  s.description = %q{Wepawet is a service for detecting and analyzing web-based malware. It currently handles Flash, JavaScript, and PDF files. http://wepawet.cs.ucsb.edu}
  s.email = %q{rubygems@chrislee.dhs.org}
  s.executables = ["wepawet"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/wepawet",
    "lib/wepawet.rb",
    "lib/wepawet/wepawet.rb",
    "test/helper.rb",
    "test/test_wepawet.rb",
    "wepawet.gemspec"
  ]
  s.homepage = %q{http://github.com/chrislee35/wepawet}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.7.2}
  # s.signing_key = %q{/Users/chris/Documents/projects/rubygems/wepawet/../gem-private_key.pem}
  s.summary = %q{provides an interface to UCSB's wepawet malicious URL analysis project}
  s.test_files = [
    "test/helper.rb",
    "test/test_wepawet.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<multipart-post>, [">= 1.1.0"])
      s.add_runtime_dependency(%q<libxml-ruby>, [">= 1.1.4"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<multipart-post>, [">= 1.1.0"])
      s.add_runtime_dependency(%q<libxml-ruby>, [">= 1.1.4"])
    else
      s.add_dependency(%q<multipart-post>, [">= 1.1.0"])
      s.add_dependency(%q<libxml-ruby>, [">= 1.1.4"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<multipart-post>, [">= 1.1.0"])
      s.add_dependency(%q<libxml-ruby>, [">= 1.1.4"])
    end
  else
    s.add_dependency(%q<multipart-post>, [">= 1.1.0"])
    s.add_dependency(%q<libxml-ruby>, [">= 1.1.4"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<multipart-post>, [">= 1.1.0"])
    s.add_dependency(%q<libxml-ruby>, [">= 1.1.4"])
  end
end
